Menu-branch
ikoote1/Portfolio-Setup pull request #7
Opened 2023-01-30 15:47 UTC by ikoote1

#MENU
- Created a menu-branch
- Added Javascript linter files
- Added Javascript file.
- Added Javascript code for the mobile menu.

2023-01-30 16:58 UTC, Ibizugbe requested changes
Hi @ikoote1 👋, 

![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d](https://user-images.githubusercontent.com/64643995/215544715-48032d06-e322-4dd4-b067-6c5c589f7ed9.gif)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights✅
- Mobile menu looks like the design.👍
- Github flow has been used.👍
- Project is well documented.👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-30 16:58 UTC, Ibizugbe commented on .eslintrc.json
> +  }
You have done a great job adding the `.eslintrc` file but you haven't done the installation. don't forget that it is a [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md) that this project has the eslint checked among the linters. 😉
![linters_reqr](https://user-images.githubusercontent.com/64643995/215539209-7bb23700-0e04-40d6-8d76-addec04e6684.png)

Your linter check is currently missing the eslint check
![Screenshot from 2023-01-30 17-42-49](https://user-images.githubusercontent.com/64643995/215539892-1c9e48e0-10a4-49cc-a3e4-ce65b9f612fc.png)

Kindly make the necessary adjustments😉

2023-01-30 16:58 UTC, Ibizugbe commented on style.css
> +}
Nice work implementing the mobile menu😉 But I think we can make it look even more like the design by giving the height property `height:100vh`  as it is a core requrement that we stick to the [design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471&t=1BajKMlmZn1jT0dS-0)

design menu
![fullwidth](https://user-images.githubusercontent.com/64643995/215542381-b5558918-3bbc-43c8-8efe-da2b98a9a816.png)

your menu
![image](https://user-images.githubusercontent.com/64643995/215542710-f7a65686-7796-4927-b4a8-651cd4ae589a.png)

kindly make the necessary changes😉

2023-01-31 07:44 UTC, AmaduKamara approved these changes
# Status: Approved 🟢 🟢 🟢 

Hi @ikoote1,

Good job working on the changes asked by the previous reviewer!

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You used Gitflow correctly 👍🏽
✅ Linter checks passed 👍🏽
✅ Mobile menu works fine as expected 👍🏽

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-31 07:46 UTC, merged